---
application:
  name: "union-booth"
  project: "union-booth"
  organization: "QoveryCommunity"
  storage:
  - name: "static"
    size: "10GB"
    type: "ssd"
    mount_point: "/mnt/static"
databases:
- type: "postgresql"
  name: "union-booth-postgres"
  version: 12
- type: "redis"
  name: "union-booth-redis"
  version: 6
routers:
- name: "main-union-booth"
  routes:
  - application_name: "union-booth"
    paths:
    - "/*"
