---
application:
  name: "union-booth"
  project: "union-booth"
  organization: "QoveryCommunity"
  storage:
  - name: "static"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/static"
databases:
- type: "POSTGRESQL"
  name: "union-booth"
  version: "11"
routers:
- name: "main-union-booth"
  routes:
  - application_name: "union-booth"
    paths:
    - "/*"
