---
application:
  name: "union-booth"
  project: "union-booth"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "union-booth"
  version: "11"
routers:
- name: "main-union-booth"
  routes:
  - application_name: "union-booth"
    paths:
    - "/*"
